apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
spec:
  rules:
  - host: myapp.com
    http:
      paths:
      - pathType: Prefix
        path: "/cart"
        backend:
          service:
            name: svc1
            port:
              number: 80
      - pathType: Prefix
        path: "/products"
        backend:
          service:
            name: svc2
            port:
              number: 80
